//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKutuphane.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UyeBilgileri
    {
        public int Id { get; set; }
        public string KullaniciAdi { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string KullaniciSifre { get; set; }
        [NotMapped]
        public string KullaniciSifreTekrar { get; set; }
        public string KullaniciTC { get; set; }
        public string KullaniciTelefon { get; set; }
        public Nullable<int> KitapId { get; set; }
        public Nullable<System.DateTime> KitapAlımTarihi { get; set; }
        public Nullable<int> Ceza { get; set; }
    }
}
