//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKutuphane.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UyeBilgileri
    {
        public int KullaniciId { get; set; }

        [Display(Name = "Kullanýcý Adý")]
        public string KullaniciAdi { get; set; }

        public string Ad { get; set; }

        public string Soyad { get; set; }

        [DataType(DataType.Password)]
        public string KullaniciSifre { get; set; }

        [DataType(DataType.Password)]
        [NotMapped]//veri tabanýndaki bir özellikle eþleþmeyecek
        public string KullaniciSifreTekrar { get; set; }

        [Display(Name = "TC")]
        public string KullaniciTC { get; set; }

        [Display(Name = "Telefon")]
        public string KullaniciTelefon { get; set; }
        public Nullable<int> KitapId { get; set; }
    }
}
